package com.streetkube.kubejsgui.tags;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import com.streetkube.kubejsgui.platform.PlatformHelper;

/**
 * Writes tag operations to disk: always a {@code type;startup} .kubeguitemplate in the
 * instance-local {@code kubejs/kubejs_gui_templates/tagTemplates/} folder, and optionally
 * the runnable {@code .js} in {@code kubejs/startup_scripts/generated/}.
 */
public final class TagTemplateWriter {

    public static final class Result {
        public String templatePath;
        public String scriptPath; // null when not generated
    }

    private TagTemplateWriter() {
    }

    public static Result write(String scriptId, String tagType, String operation, String tagId,
                               List<String> members, String author, String description,
                               boolean alsoGenerateScript) throws IOException {
        Path gameDir = PlatformHelper.getGameDir();
        Path kubejs = gameDir.resolve("kubejs");

        Path tplDir = kubejs.resolve("kubejs_gui_templates").resolve("tagTemplates");
        Files.createDirectories(tplDir);
        Path tplPath = safeResolve(tplDir, scriptId + ".kubeguitemplate");
        String script = TagScriptGenerator.generate(tagType, operation, tagId, members);
        Files.writeString(tplPath, buildTemplate(scriptId, author, description, script),
                StandardCharsets.UTF_8);

        Result result = new Result();
        result.templatePath = rel(gameDir, tplPath);

        if (alsoGenerateScript) {
            Path scriptDir = kubejs.resolve("startup_scripts").resolve("generated");
            Files.createDirectories(scriptDir);
            Path scriptPath = safeResolve(scriptDir, scriptId + ".js");
            Files.writeString(scriptPath, script, StandardCharsets.UTF_8);
            result.scriptPath = rel(gameDir, scriptPath);
        }
        return result;
    }

    private static String buildTemplate(String name, String author, String description, String script) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by KubeJS GUI 2 — Tags\n\n# --- METADATA ---\n");
        sb.append("name;").append(sanitizeMeta(name)).append('\n');
        sb.append("author;").append(sanitizeMeta(author.isBlank() ? "unknown" : author)).append('\n');
        sb.append("version;1.0.0\n");
        sb.append("type;startup\n");
        if (description != null && !description.isBlank()) {
            sb.append("description;").append(sanitizeMeta(description)).append('\n');
        }
        sb.append("\n# --- SCRIPT ---\nSCRIPT_START\n").append(script);
        if (!script.endsWith("\n")) {
            sb.append('\n');
        }
        sb.append("SCRIPT_END\n");
        return sb.toString();
    }

    private static Path safeResolve(Path dir, String fileName) throws IOException {
        Path resolved = dir.resolve(fileName).normalize();
        if (!resolved.startsWith(dir.normalize())) {
            throw new IOException("Path traversal attempt rejected");
        }
        return resolved;
    }

    private static String rel(Path gameDir, Path file) {
        return gameDir.relativize(file).toString().replace('\\', '/');
    }

    private static String sanitizeMeta(String s) {
        return s.replaceAll("[;\\r\\n]", " ");
    }
}
