package com.streetkube.kubejsgui.server;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import net.minecraft.network.chat.Component;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;

import java.io.IOException;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import com.streetkube.kubejsgui.platform.PlatformHelper;

/**
 * Raw Script tab save endpoint:
 * <ul>
 *   <li>POST /rawscript/save?name=&amp;type=&amp;author= - body is the raw script.</li>
 * </ul>
 *
 * <p>Always writes a {@code .kubeguitemplate} (with metadata, including {@code type}) to the
 * instance templates folder. For type {@code server|client|startup} it additionally writes the
 * raw script as {@code <name>.js} into the matching {@code kubejs/<type>_scripts/} folder.
 */
public final class RawScriptHandler implements HttpHandler {

    private static final Gson GSON = new Gson();
    private static final Set<String> TYPES = Set.of("server", "client", "startup", "template");

    @Override
    public void handle(HttpExchange exchange) throws IOException {
        if (!"POST".equals(exchange.getRequestMethod())
                || !exchange.getRequestURI().getPath().equals("/rawscript/save")) {
            error(exchange, 404, "not found");
            return;
        }
        try {
            Map<String, String> query = parseQuery(exchange);
            String displayName = query.getOrDefault("name", "").trim();
            String type = query.getOrDefault("type", "server").trim();
            String author = query.getOrDefault("author", "").trim();
            if (author.isEmpty()) {
                author = "unknown";
            }
            String safe = displayName.replaceAll("[^a-zA-Z0-9_\\-]", "_");
            if (safe.isEmpty()) {
                error(exchange, 400, "Name is empty or has no usable characters");
                return;
            }
            if (!TYPES.contains(type)) {
                error(exchange, 400, "Invalid type");
                return;
            }

            String script = new String(exchange.getRequestBody().readAllBytes(), StandardCharsets.UTF_8);
            String metaName = displayName.replaceAll("[;\\r\\n]", " ");

            Path gameDir = PlatformHelper.getGameDir();
            Path kubejs = gameDir.resolve("kubejs");

            // 1) Always write the template (with metadata).
            String template = buildTemplate(metaName, author, type, script);
            Path tplDir = kubejs.resolve("kubejs_gui_templates");
            Files.createDirectories(tplDir);
            Path tplPath = tplDir.resolve(safe + ".kubeguitemplate");
            Files.writeString(tplPath, template, StandardCharsets.UTF_8);

            // 2) For script types, also write the runnable .js.
            String scriptRel = null;
            if (!type.equals("template")) {
                Path scriptDir = kubejs.resolve(type + "_scripts");
                Files.createDirectories(scriptDir);
                Path scriptPath = scriptDir.resolve(safe + ".js");
                Files.writeString(scriptPath, script, StandardCharsets.UTF_8);
                scriptRel = gameDir.relativize(scriptPath).toString().replace('\\', '/');
            }

            String tplRel = gameDir.relativize(tplPath).toString().replace('\\', '/');
            notifyPlayers(safe, type, scriptRel);

            JsonObject json = new JsonObject();
            json.addProperty("success", true);
            json.addProperty("templatePath", tplRel);
            if (scriptRel != null) {
                json.addProperty("scriptPath", scriptRel);
            }
            ScriptBuilderServer.sendText(exchange, 200, "application/json", GSON.toJson(json));
        } catch (IOException e) {
            error(exchange, 500, "Write failed: " + e.getMessage());
        }
    }

    private static String buildTemplate(String name, String author, String type, String script) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by KubeJS GUI 2\n\n# --- METADATA ---\n");
        sb.append("name;").append(name).append('\n');
        sb.append("author;").append(author).append('\n');
        sb.append("version;1.0.0\n");
        sb.append("type;").append(type).append('\n');
        sb.append("\n# --- SCRIPT ---\nSCRIPT_START\n").append(script);
        if (!script.endsWith("\n")) {
            sb.append('\n');
        }
        sb.append("SCRIPT_END\n");
        return sb.toString();
    }

    private void notifyPlayers(String name, String type, String scriptRel) {
        MinecraftServer server = PlatformHelper.getServer();
        if (server == null) {
            return;
        }
        server.execute(() -> {
            String msg;
            if (scriptRel == null) {
                msg = "[KubeJS GUI] Template '" + name + "' saved.";
            } else {
                String reload = "startup".equals(type)
                        ? "Restart the game to apply."
                        : "Run /kubejs reload to apply.";
                msg = "[KubeJS GUI] " + name + ".js written to " + type + "_scripts. " + reload;
            }
            Component message = Component.literal(msg);
            for (ServerPlayer player : server.getPlayerList().getPlayers()) {
                player.sendSystemMessage(message);
            }
        });
    }

    private void error(HttpExchange exchange, int status, String message) throws IOException {
        JsonObject json = new JsonObject();
        json.addProperty("success", false);
        json.addProperty("error", message);
        ScriptBuilderServer.sendText(exchange, status, "application/json", GSON.toJson(json));
    }

    private static Map<String, String> parseQuery(HttpExchange exchange) {
        Map<String, String> result = new HashMap<>();
        String raw = exchange.getRequestURI().getRawQuery();
        if (raw == null || raw.isEmpty()) {
            return result;
        }
        for (String pair : raw.split("&")) {
            int eq = pair.indexOf('=');
            if (eq < 0) {
                result.put(decode(pair), "");
            } else {
                result.put(decode(pair.substring(0, eq)), decode(pair.substring(eq + 1)));
            }
        }
        return result;
    }

    private static String decode(String s) {
        return URLDecoder.decode(s, StandardCharsets.UTF_8);
    }
}
