package com.streetkube.kubejsgui.template;

import java.util.Map;

/**
 * Serializes a {@link TemplateFile} back to .kubeguitemplate text. The output is
 * semantically equivalent to a parsed file (round-trips through {@link TemplateParser}).
 */
public final class TemplateSerializer {

    private TemplateSerializer() {
    }

    public static String serialize(TemplateFile file) {
        StringBuilder sb = new StringBuilder();

        sb.append("# Generated by KubeJS GUI Template Builder\n\n");

        sb.append("# --- METADATA ---\n");
        for (Map.Entry<String, String> entry : file.getMetadata().entrySet()) {
            sb.append(entry.getKey()).append(';').append(entry.getValue()).append('\n');
        }
        sb.append('\n');

        sb.append("# --- CANVAS ELEMENTS ---\n");
        for (TemplateElement element : file.getElements()) {
            sb.append(element.toLine()).append('\n');
        }
        sb.append('\n');

        sb.append("# --- SCRIPT ---\n");
        sb.append("SCRIPT_START\n");
        sb.append(file.getScriptTemplate());
        if (!file.getScriptTemplate().endsWith("\n")) {
            sb.append('\n');
        }
        sb.append("SCRIPT_END\n");

        return sb.toString();
    }
}
